# Generated by Django 4.2.9 on 2024-01-25 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=250)),
                ('location', models.CharField(default='', max_length=150)),
                ('location_link', models.CharField(default='', help_text='Link od Google Maps od vasata adresa', max_length=150)),
                ('logo', models.ImageField(blank=True, default='default.jpg', upload_to='shop_logos')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
