# Generated by Django 4.2.9 on 2024-01-26 09:12

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2024, 1, 26), help_text='eg. 23-11-2023', validators=[django.core.validators.MinValueValidator(datetime.date(2024, 1, 26)), django.core.validators.MaxValueValidator(datetime.date(2024, 2, 25))])),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('total_price', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('services', models.ManyToManyField(to='services.service')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
