# Generated by Django 4.2.9 on 2024-01-28 10:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 28), help_text='eg. 23-11-2023', validators=[django.core.validators.MinValueValidator(datetime.date(2024, 1, 28)), django.core.validators.MaxValueValidator(datetime.date(2024, 2, 27))]),
        ),
    ]
