# Generated by Django 4.2.9 on 2024-01-31 08:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_code_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 8, 28, 24, 19069, tzinfo=datetime.timezone.utc), help_text='eg. 23-11-2023', validators=[django.core.validators.MinValueValidator(datetime.date(2024, 1, 31)), django.core.validators.MaxValueValidator(datetime.date(2024, 3, 1))]),
        ),
    ]
