# Generated by Django 4.2.9 on 2024-01-31 08:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 8, 30, 23, 692703, tzinfo=datetime.timezone.utc), help_text='eg. 23-11-2023', validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 1, 31, 8, 30, 23, 692703, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(datetime.datetime(2024, 3, 1, 8, 30, 23, 692703, tzinfo=datetime.timezone.utc))]),
        ),
    ]
