# Generated by Django 4.2.9 on 2024-06-13 08:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 23-11-2023', validators=[django.core.validators.MinValueValidator(datetime.date(2024, 6, 13)), django.core.validators.MaxValueValidator(datetime.date(2024, 7, 13))]),
        ),
    ]
